# Generated by Django 5.2.1 on 2025-05-12 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_sluggedtag_alter_courseinvitation_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinvitation',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 7, 31, 24, 495690, tzinfo=datetime.timezone.utc)),
        ),
    ]
