# Generated by Django 5.2.1 on 2025-05-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_quiz_publish_alter_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('short', 'Short Answer'), ('long', 'Long Answer'), ('choice', 'Multiple Choice')], max_length=20),
        ),
    ]
